### ISSUE TITLE
 /usr/share/glib-2.0/schemas/org.ayatana.indicator.datetime.gschema.xml:4:1 Error on line 4 char 1: <enum id='time-enum'> already specified. This entire file has been ignored

### ISSUE THREAD

**Issue by N0rbert** [AyatanaIndicators/ayatana-indicator-datetime#15]
Steps to reproduce:
1. Have Ubuntu MATE 20.10 installed
2. Upgrade or install some package which have glib triggers

Expected result:
* no error messages in APT/dpkg output

Actual result:

```
Processing triggers for libglib2.0-0:amd64 (2.64.4-1) ...
/usr/share/glib-2.0/schemas/org.ayatana.indicator.datetime.gschema.xml:4:1  Error on line 4 char 1: <enum id='time-enum'> already specified.  This entire file has been ignored.

```

Downstream bug-report: 

https://bugs.launchpad.net/ubuntu/+source/ayatana-indicator-datetime/+bug/1893028

**Comment by sunweaver** [comment]
@N0rbert: thanks for upstreaming that Launchpad issue report.

One could say, this is simply a packaging issue (which falls back on me, too, I guess). Maybe we should simply add a  Breaks:/Replaces: against all indicator-datetime versions from Ubuntu Indicators. We had to do this with other indicators already, as well (like the -session indicator, because of icon artwork, iirc).

Another solution, would be renaming the enum iterator field in the Ayatana -datetime indicator's gschema file. This would be an upstream change only required for Ubuntu.

The disadvantage of simply doing a Breaks:/Replaces: thingy in debian/control is that it will bite people who want to install a desktop running on Ayatana Indicators and a desktop powered by Ubuntu Indicators alongside one another. With a B:/R: statement, packages (ayatana-indicator-* <-> indicator-*) will be mutually exclusive.

Another fix could be to rename the iterator for a while in the Debian/Ubuntu packaging via a patch in debian/patches (in the distro packaging). But again, we have a B:/R: for other system indicators already in place.

@flexiondotorg @tar01 please provide your feedback on this... Thanks!

**Comment by tari01** [comment]
Normally, I'm all against breaks/replaces for reasons mentioned above. On the other hand, Ayatana is destined to replace legacy indicators at one point. If other indicators already do the b/r, I say we need not worry about this one's co-existence.

**Comment by saivinoba** [comment]
It took me some time to digest both of your comments. :-) I can confirm, issue https://github.com/AyatanaIndicators/ayatana-indicator-datetime/issues/16 is resolved if we remove indicator-datetime package.
