### ISSUE TITLE
why there are dependencies on unity libraries in Ubuntu?

### ISSUE THREAD

**Issue by colourful-land** [AyatanaIndicators/ayatana-indicator-datetime#21]
Observed that ayatana indictors typically don't depend on unity. e.g.

- ayatana-indicator-sound depends on ayatana-indicator-common only
- ayatana-indicator-application depends on ayatana-indicator-common libayatana-appindicator3-1 libayatana-ido3-0.4-0 libayatana-indicator3-7

However, on Ubuntu 20.10, ayatana-indicator-datetime has a huge dependency

````
  accountsservice-ubuntu-schemas ayatana-indicator-common ayatana-indicator-datetime bamfdaemon gnome-screensaver indicator-applet
  indicator-application indicator-appmenu indicator-bluetooth indicator-common indicator-datetime indicator-keyboard
  indicator-messages indicator-power indicator-printers indicator-session indicator-sound jayatana libaccounts-glib0 libbamf3-2
  libgnome-panel0 libido3-0.1-0 libindicator3-7 liblightdm-gobject-1-0 libunity-gtk2-parser0 libunity-gtk3-parser0
  ubuntu-touch-sounds unity-gtk-module-common unity-gtk2-module unity-gtk3-module unity-settings-daemon-schemas
````

One guess is legacy code using these stuff, right?

Regards

**Comment by tari01** [comment]
@colourful-land 

The ayatana-indicator-datetime service built by this code definitely does not require anything Unity-specific. I have also checked the Debian [control file](https://github.com/AyatanaIndicators/ayatana-indicator-datetime/blob/master/debian/control) for the built package - in your case it is pulling in **indicator-applet**, and that package is further responsible for the mess.

You will be experiencing this as long as **indicator-applet** depends on the old Ubuntu indicator packages. Once they switch to Ayatana the dependecies will be gone.

I am closing this because the bug is not on the Ayatana side.
