### ISSUE TITLE
Lomiri: Alarm date & time previews don't take timezone into account

### ISSUE THREAD

**Issue by JamiKettunen** [AyatanaIndicators/ayatana-indicator-datetime#98]
On Ubuntu Touch 20.04 alarms set with [Clock app](https://gitlab.com/ubports/development/apps/clock-app/-/merge_requests/198) show up in the datetime indicator widgets, but the dates aren't correct at all even though the time itself at least seems to take timezone into account in some form (unlike #97), but still seems wrong too (`UTC+3` offset is 3 hours from `UTC+0`, but the time shows `02:00` and changing timezone to `UTC+1` only changed it to `01:00` interestingly enough):
<img src="https://user-images.githubusercontent.com/47358222/189361064-a89056d7-cd76-44c6-9afa-16fda3818297.png" width=400 />
This should be reproducible with [the UBports PDK](https://github.com/ubports/ubports-pdk) but I didn't check, only on hardware (Volla Phone w/ UT 20.04).

Comparison picture from Ubuntu Touch 16.04:
<img src="https://user-images.githubusercontent.com/47358222/189367369-c43b9d20-40a7-4bce-a258-dbe238a5fbae.png" width=400 />

**Comment by tari01** [comment]
@JamiKettunen @sunweaver 

I have tested this thoroughly, the indicator is fine. It sends the right Unix time onto the bus. The problem seems to be in the qml world in Lomiri, starting with the `alarmMenu` class/property/interface? in https://gitlab.com/ubports/development/core/lomiri/-/blob/main/qml/Panel/Indicators/IndicatorMenuItemFactory.qml#L500.

There are some `x-canonical-*` properties in there that look suspicious, but I would prefer if somebody with a decent understanding of QML could look into that.

**Comment by sunweaver** [comment]
x-canoncal-* to x-lomiri-* related issues:
https://github.com/ubports/unity8/pull/441
aka https://gitlab.com/ubports/development/core/lomiri/-/issues/31

and also
https://gitlab.com/ubports/development/core/lomiri/-/issues/33

**Comment by sunweaver** [comment]
@JamiKettunen @mariogrip ^^^

**Comment by mariogrip** [comment]
This seems fine for me now on latest rev

**Comment by mariogrip** [comment]
But it does show one hour later then it should, so something is fishy here

**Comment by JamiKettunen** [comment]
Can confirm @mariogrip's latest findings on UT 20.04 with both Volla Phone (r346) and Volla Phone 22 (r37). It looks like the timezone isn't being taken into account now as similarly reported on #97 previously (in my case on a device with properly configured timezone the indicator shows the alarm being 2 hours in the future, but with UTC it works as seen on 16.04), wonder what exactly fixed the other issue...

**Comment by peat-psuwit** [comment]
Turns out, the alarm being in the wrong timezone is the fault of [qtorganizer5-eds](https://gitlab.com/ubports/development/core/qtorganizer5-eds/-/merge_requests/17). ayatana-indicator-datetime is actually doing its job correctly here.

And since the problem that the time stuck in Jan 1 1970 is also fixed, I'll now close this issue.
